Final_Project_PRN/Pages/Class/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Final_Project_PRN.Models;

namespace Final_Project_PRN.Pages.Class
{
    public class CreateModel : PageModel
    {
        private readonly Final_Project_PRN.Models.PRN221ProjectContext _context;

        public CreateModel(Final_Project_PRN.Models.PRN221ProjectContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public UniversityClass UniversityClass { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.UniversityClasses == null || UniversityClass == null)
            {
                return Page();
            }

            _context.UniversityClasses.Add(UniversityClass);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Final_Project_PRN/Pages/Class/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Final_Project_PRN.Models;

namespace Final_Project_PRN.Pages.Class
{
    public class DeleteModel : PageModel
    {
        private readonly Final_Project_PRN.Models.PRN221ProjectContext _context;

        public DeleteModel(Final_Project_PRN.Models.PRN221ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
      public UniversityClass UniversityClass { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null || _context.UniversityClasses == null)
            {
                return NotFound();
            }

            var universityclass = await _context.UniversityClasses.FirstOrDefaultAsync(m => m.ClassId == id);

            if (universityclass == null)
            {
                return NotFound();
            }
            else 
            {
                UniversityClass = universityclass;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null || _context.UniversityClasses == null)
            {
                return NotFound();
            }
            var universityclass = await _context.UniversityClasses.FindAsync(id);

            if (universityclass != null)
            {
                UniversityClass = universityclass;
                _context.UniversityClasses.Remove(UniversityClass);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Final_Project_PRN/Pages/Class/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Final_Project_PRN.Models;

namespace Final_Project_PRN.Pages.Class
{
    public class DetailsModel : PageModel
    {
        private readonly Final_Project_PRN.Models.PRN221ProjectContext _context;

        public DetailsModel(Final_Project_PRN.Models.PRN221ProjectContext context)
        {
            _context = context;
        }

      public UniversityClass UniversityClass { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null || _context.UniversityClasses == null)
            {
                return NotFound();
            }

            var universityclass = await _context.UniversityClasses.FirstOrDefaultAsync(m => m.ClassId == id);
            if (universityclass == null)
            {
                return NotFound();
            }
            else 
            {
                UniversityClass = universityclass;
            }
            return Page();
        }
    }
}

Final_Project_PRN/Pages/Class/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Final_Project_PRN.Models;

namespace Final_Project_PRN.Pages.Class
{
    public class EditModel : PageModel
    {
        private readonly Final_Project_PRN.Models.PRN221ProjectContext _context;

        public EditModel(Final_Project_PRN.Models.PRN221ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public UniversityClass UniversityClass { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null || _context.UniversityClasses == null)
            {
                return NotFound();
            }

            var universityclass =  await _context.UniversityClasses.FirstOrDefaultAsync(m => m.ClassId == id);
            if (universityclass == null)
            {
                return NotFound();
            }
            UniversityClass = universityclass;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(UniversityClass).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UniversityClassExists(UniversityClass.ClassId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool UniversityClassExists(string id)
        {
          return (_context.UniversityClasses?.Any(e => e.ClassId == id)).GetValueOrDefault();
        }
    }
}

Final_Project_PRN/Pages/Schedules/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Final_Project_PRN.Models;

namespace Final_Project_PRN.Pages.Schedules
{
    public class CreateModel : PageModel
    {
        private readonly Final_Project_PRN.Models.PRN221ProjectContext _context;

        public CreateModel(Final_Project_PRN.Models.PRN221ProjectContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["ClassId"] = new SelectList(_context.UniversityClasses, "ClassId", "ClassId");
        ViewData["SubjectId"] = new SelectList(_context.Subjects, "SubjectId", "SubjectId");
        ViewData["Teacher"] = new SelectList(_context.Teachers, "TeacherId", "TeacherId");
            return Page();
        }

        [BindProperty]
        public Schedule Schedule { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Schedules == null || Schedule == null)
            {
                return Page();
            }

            _context.Schedules.Add(Schedule);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Final_Project_PRN/Pages/Schedules/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Final_Project_PRN.Models;

namespace Final_Project_PRN.Pages.Schedules
{
    public class DeleteModel : PageModel
    {
        private readonly Final_Project_PRN.Models.PRN221ProjectContext _context;

        public DeleteModel(Final_Project_PRN.Models.PRN221ProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Schedule Schedule { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Schedules == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedules.FirstOrDefaultAsync(m => m.Id == id);

            if (schedule == null)
            {
                return NotFound();
            }
            else 
            {
                Schedule = schedule;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Schedules == null)
            {
                return NotFound();
            }
            var schedule = await _context.Schedules.FindAsync(id);

            if (schedule != null)
            {
                Schedule = schedule;
                _context.Schedules.Remove(Schedule);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Final_Project_PRN/Pages/Schedules/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Final_Project_PRN.Models;

namespace Final_Project_PRN.Pages.Schedules
{
    public class DetailsModel : PageModel
    {
        private readonly Final_Project_PRN.Models.PRN221ProjectContext _context;

        public DetailsModel(Final_Project_PRN.Models.PRN221ProjectContext context)
        {
            _context = context;
        }

      public Schedule Schedule { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Schedules == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedules.FirstOrDefaultAsync(m => m.Id == id);
            if (schedule == null)
            {
                return NotFound();
            }
            else 
            {
                Schedule = schedule;
            }
            return Page();
        }
    }
}

Final_Project_PRN/Pages/Schedules/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Final_Project_PRN.Models;
using Final_Project_PRN.Pages.Common;
using Final_Project_PRN.Pages.Validate;
using Microsoft.Extensions.Hosting;
using static Final_Project_PRN.Pages.Common.EnumPrototype;
using System.Formats.Asn1;
using System.IO;
using System.Globalization;
using CsvHelper;
using System.Text.Json;
using Final_Project_PRN.Services;
using Schedule_Project.DTOs;

namespace Final_Project_PRN.Pages.Schedules
{
    public class IndexModel : PageModel
    {
        private readonly IWebHostEnvironment _environment;
        private ScheduleService ScheduleService;
        private TeacherServices TeacherServices;
        private SubjectService SubjectService;
        private UniversityClassService UniversityClassService;
        private CourseSessionService CourseSessionService;
        private ValidateSchedule ValidateSchedule;

        private readonly Final_Project_PRN.Models.PRN221ProjectContext _context;

        public List<ScheduleDTO> ScheduleDTO { get; set; }
        public Dictionary<int, Tuple<ScheduleDTO,string>> ImportStatus = new Dictionary<int, Tuple<ScheduleDTO, string>>();
        public Dictionary<Tuple<string, int>, DisplayCell> dictionary = new Dictionary<Tuple<string, int>, DisplayCell>();
        public DateTime SelectedDate { get; set; }
        [BindProperty]
        public IFormFile FileUpload { get; set; }
        public IndexModel(Final_Project_PRN.Models.PRN221ProjectContext context, IWebHostEnvironment environment,
            ScheduleService scheduleService, TeacherServices teacherServices, SubjectService subjectService, UniversityClassService uni, CourseSessionService courseSessionService, ValidateSchedule validateSchedule)
        {
            _context = context;
            _environment = environment;
            ScheduleService = scheduleService;
            TeacherServices = teacherServices;
            SubjectService = subjectService;
            UniversityClassService = uni;
            CourseSessionService = courseSessionService;
            ValidateSchedule = validateSchedule;
        }
        public HashSet<String> RoomInSchedule { get; set; } = default!;
        public void OnGet()
        {
            SelectedDate = DateTime.Now;
            GetListSession(SelectedDate);
        }

        public void OnPostDate(DateTime dadate)
        {
            SelectedDate = dadate;
            GetListSession(SelectedDate);
        }

        public IActionResult OnPostImport()
        {
            string message = ValidateFile.validate(FileUpload);
            if(!message.Equals("Import OK"))
            {
                TempData["Message"] = message;
                return Page();
            }
            ScheduleDTO = SaveFile();
            validateScheList(ScheduleDTO);
            PopulateSessions();
            TempData["Result"] = JsonSerializer.Serialize(ImportStatus);
            return RedirectToPage("/Import/ImportResult");
        }
        private void PopulateSessions()
        {
            foreach(Schedule schedule in ScheduleService.Schedules)
            {
                //chua co session thi populate
                if(!schedule.HasSessionYet)
                {
                    CourseSessionService.ImportEachSession(schedule);
                }
            }
        }
        private void validateScheList(List<ScheduleDTO> dtos)
        {
            int ind = 0;
            foreach (ScheduleDTO dto in dtos)
            {
                Tuple<ScheduleDTO, string> value = Tuple.Create(dto, ValidateSchedule.validate(dto));
                ImportStatus.Add(ind, value);
                //add dto to list of schedule
                if(value.Item2.Equals("Schedule OK"))
                ScheduleService.CreateSchedule(dto);
                ind++;
            }
        }
        private List<ScheduleDTO> SaveFile()
        {
            var uploadsFolder = Path.Combine(_environment.WebRootPath, "fileuploaded");
            if (!Directory.Exists(uploadsFolder))
            {
                Directory.CreateDirectory(uploadsFolder);
            }

            var filePath = Path.Combine(uploadsFolder, FileUpload.FileName);
            string fileType = Path.GetExtension(FileUpload.FileName);
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                FileUpload.CopyTo(stream);
            }
            return FileToScheduleDTO(filePath, fileType);
        }
        private List<ScheduleDTO> FileToScheduleDTO(string filePath, string fileType)
        {
            List<ScheduleDTO> scheduleDTOs;
            switch (fileType)
            {
                case ".json":
                    scheduleDTOs = DeserializeToJSON(filePath);
                    break;
                case ".csv":
                    scheduleDTOs = DeserialiseCSV(filePath);
                    break;
                case ".xml":
                default:
                    scheduleDTOs = new List<ScheduleDTO>();
                    break;
            }

            return scheduleDTOs;
        }

        private List<ScheduleDTO> DeserializeToJSON(string filePath)
        {
            string json = System.IO.File.ReadAllText(filePath);
            List<ScheduleDTO> scheduleDTOs = JsonSerializer.Deserialize<List<ScheduleDTO>>(json);
            return scheduleDTOs;
        }

        private List<ScheduleDTO> DeserialiseCSV(string filePath)
        {
            var scheduleDTOs = new List<ScheduleDTO>();
            if (!System.IO.File.Exists(filePath)) return new List<ScheduleDTO>();
            var reader = new StreamReader(filePath);
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                scheduleDTOs = csv.GetRecords<ScheduleDTO>().ToList();
            }
            return scheduleDTOs.ToList();
        }
        private void GetListSession(DateTime SelectedDate)
        {
            var Session = _context.CourseSessions.Include(courseSession => courseSession.Course).Where(d => d.SessionDate == SelectedDate).ToList();
            RoomInSchedule = Session.Select(x => x.Room).ToHashSet();
            foreach (var session in Session)
            {
                var key = new Tuple<string, int>(session.Room, session.Slot);
                DisplayCell value = new(0,session.Course.ClassId, session.Course.SubjectId, session.Course.Teacher);
                dictionary.Add(key, value);
            }
        }


    }
}

Final_Project_PRN/Pages/Schedules/Create.cshtml
@page
@model Final_Project_PRN.Pages.Schedules.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Schedule</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Schedule.ClassId" class="control-label"></label>
                <select asp-for="Schedule.ClassId" class ="form-control" asp-items="ViewBag.ClassId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Schedule.SubjectId" class="control-label"></label>
                <select asp-for="Schedule.SubjectId" class ="form-control" asp-items="ViewBag.SubjectId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Schedule.Room" class="control-label"></label>
                <input asp-for="Schedule.Room" class="form-control" />
                <span asp-validation-for="Schedule.Room" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Schedule.Teacher" class="control-label"></label>
                <select asp-for="Schedule.Teacher" class ="form-control" asp-items="ViewBag.Teacher"></select>
            </div>
            <div class="form-group">
                <label asp-for="Schedule.SlotId" class="control-label"></label>
                <input asp-for="Schedule.SlotId" class="form-control" />
                <span asp-validation-for="Schedule.SlotId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Schedule.DateCreated" class="control-label"></label>
                <input asp-for="Schedule.DateCreated" class="form-control" />
                <span asp-validation-for="Schedule.DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Schedule.Season" class="control-label"></label>
                <input asp-for="Schedule.Season" class="form-control" />
                <span asp-validation-for="Schedule.Season" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Schedule.Year" class="control-label"></label>
                <input asp-for="Schedule.Year" class="form-control" />
                <span asp-validation-for="Schedule.Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Schedule.StartDate" class="control-label"></label>
                <input asp-for="Schedule.StartDate" class="form-control" />
                <span asp-validation-for="Schedule.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Schedule.EndDate" class="control-label"></label>
                <input asp-for="Schedule.EndDate" class="form-control" />
                <span asp-validation-for="Schedule.EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Schedule.TypeOfSlot" class="control-label"></label>
                <input asp-for="Schedule.TypeOfSlot" class="form-control" />
                <span asp-validation-for="Schedule.TypeOfSlot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Schedule.Slot1" class="control-label"></label>
                <input asp-for="Schedule.Slot1" class="form-control" />
                <span asp-validation-for="Schedule.Slot1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Schedule.Slot2" class="control-label"></label>
                <input asp-for="Schedule.Slot2" class="form-control" />
                <span asp-validation-for="Schedule.Slot2" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Schedule.HasSessionYet" /> @Html.DisplayNameFor(model => model.Schedule.HasSessionYet)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Final_Project_PRN/Pages/Schedules/Delete.cshtml
@page
@model Final_Project_PRN.Pages.Schedules.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Schedule</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.Room)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.Room)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.SlotId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.SlotId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.DateCreated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.DateCreated)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.Season)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.Season)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.TypeOfSlot)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.TypeOfSlot)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.Slot1)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.Slot1)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.Slot2)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.Slot2)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.HasSessionYet)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.HasSessionYet)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.Class)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.Class.ClassId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.Subject)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.Subject.SubjectId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Schedule.TeacherNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Schedule.TeacherNavigation.TeacherId)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Schedule.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Final_Project_PRN/Pages/Schedules/List.cshtml
@page
@model Final_Project_PRN.Pages.Schedules.IndexModel
@{
    ViewData["Title"] = "Index";
}

<h1>Schedules</h1>
<style>

    .table td {
        border: white solid 2px;
    }

    .table td {
        text-align: center;
        vertical-align: middle;
    }

    .table tr:nth-child(2n) {
        background-color: aliceblue;
    }

    .table .header {
        background-color: cornflowerblue;
    }

    #header {
        background-color: cornflowerblue;
        font-weight: bold;
    }

    #dateth {
        text-align: center;
    }

    #createBut {
        border: black solid 2px;
        background-color: blue;
        border-radius: 10px;
        margin: 10px;
    }

        #createBut a {
            color: white;
            font-size: 20px;
            text-decoration: none;
        }

        #createBut:hover {
            background-color: dodgerblue;
        }

    #create {
        margin: 0 auto;
        width: 30%;
        height: 30%;
        position: absolute;
        z-index: 1;
        border: 1px solid black;
        border-radius: 10px;
        background-color: white;
        text-align:center;
        top: 20%;
        left: 40%;
    }
</style>
<button id="createBut">
    <a onclick="show()">Add Schedule</a>
</button>
<table class="table">
    <tr id="header">
        <form method="post" asp-page-handler="date">
        <th colspan="7" id="dateth">
            DATE: <input type="date" name="dadate" value="@Model.SelectedDate.ToString("yyyy-MM-dd")" />
            <input type="submit" value="View" style="padding-left: 10px; border-radius: 5px;" />
        </th>
        </form>
    </tr>
    <tr class="header" id="header">
        <td>Room</td>
        <td>Slot 1 <br /> (7:30 - 9:50)</td>
        <td>Slot 2 <br /> (10:00 - 12:20)</td>
        <td>Slot 3<br /> (12:50 - 15:10)</td>
        <td>Slot 4<br /> (15:20 - 17:40)</td>
        <td>Slot 5<br /> (18:00 - 20:20)</td>
        <td>Slot 6<br /> (20:20 - 22:40)</td>
    </tr>
    @{
        var dictionary = Model.dictionary;
    }
    @foreach (var room in Model.RoomInSchedule)
    {
        <tr>
            <td>@room</td>
            @for (int i = 1; i <= 6; i++)
            {

                var key = Tuple.Create(room, i);
                Common.DisplayCell value = new Common.DisplayCell();
                if (dictionary.TryGetValue(key, out value))
                {
                    <td>
                        @value.Class<br />
                        @value.Subject<br />
                        @value.Teacher
                    </td>
                }
                else
                {
                    <td></td>
                }
            }
        </tr>
    }
    <div id="create"  style="display:none">
        <form method="post" enctype="multipart/form-data" asp-page-handler="import">
            <div class="form-group">

                <label>Choose file</label><br />
                <input type="file" class="form-control-file" id="fileInput" name="FileUpload" accept=".json, .xml, .csv">
            </div>
            <button type="submit" class="btn btn-primary">Upload</button>
        </form>
    </div>
</table>
    <script>
        function show(){
            var form = document.getElementById("create");
            if (form.style.display == "block") {
                form.style.display = "none";
            }else
            form.style.display = "block";
        }
    </script>
@if (TempData["Message"] != null)
{
    <script>
        window.onload = function () {
            alert("@TempData["Message"]");
        }
    </script>
}
<script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
        integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
        crossorigin="anonymous"></script>